"""add ticket core tables

Revision ID: 88c4713c4ce7
Revises: 83006eb95bc4
Create Date: 2026-09-21 14:35:03.485092+08:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88c4713c4ce7'
down_revision: str | None = '83006eb95bc4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=50), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=30), nullable=False, comment='部门编码，如 tech'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sla_policies',
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: low/medium/high/urgent'),
    sa.Column('response_minutes', sa.Integer(), nullable=False, comment='响应时限(分钟)'),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False, comment='解决时限(分钟)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('tickets',
    sa.Column('ticket_no', sa.String(length=32), nullable=False, comment='工单编号，如 OPS-202609-000123'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='分类: account/payment/technical/logistics/operation/other'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: low/medium/high/urgent'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/processing/waiting/resolved/closed'),
    sa.Column('creator_id', sa.BigInteger(), nullable=False, comment='创建人'),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True, comment='负责人，null 表示还没分派'),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='负责部门'),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True, comment='SLA 截止时间(UTC)，由创建时的优先级决定'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='解决时间(UTC)'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='关闭时间(UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assignee_id'), 'tickets', ['assignee_id'], unique=False)
    op.create_index('ix_tickets_assignee_status', 'tickets', ['assignee_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_creator_id'), 'tickets', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_department_id'), 'tickets', ['department_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_sla_deadline'), 'tickets', ['sla_deadline'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index('ix_tickets_status_priority', 'tickets', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_no'), 'tickets', ['ticket_no'], unique=True)
    op.create_table('ticket_comments',
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='评论人'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_ticket_created', 'ticket_comments', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_table('ticket_events',
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作人，null 表示系统自动'),
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='created/updated/assigned/status_changed/priority_changed/commented'),
    sa.Column('event_data', mysql.JSON(), nullable=True, comment='事件详情(JSON)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_ticket_created', 'ticket_events', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_events_ticket_id'), 'ticket_events', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_events_ticket_id'), table_name='ticket_events')
    op.drop_index('ix_events_ticket_created', table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_index('ix_comments_ticket_created', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_tickets_ticket_no'), table_name='tickets')
    op.drop_index('ix_tickets_status_priority', table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sla_deadline'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_department_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_creator_id'), table_name='tickets')
    op.drop_index('ix_tickets_assignee_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('sla_policies')
    op.drop_table('departments')
    # ### end Alembic commands ###
