"""add agent tables

Revision ID: 30d24c5b74fc
Revises: 88c4713c4ce7
Create Date: 2026-09-21 15:10:37.613308+08:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30d24c5b74fc'
down_revision: str | None = '88c4713c4ce7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_steps',
    sa.Column('run_id', sa.String(length=36), nullable=False, comment='关联 agent_runs.run_id'),
    sa.Column('seq', sa.BigInteger(), nullable=False, comment='步骤序号，从 1 开始'),
    sa.Column('step_type', sa.String(length=20), nullable=False, comment='intent/thought/tool_call/tool_result/plan/approval/answer/error'),
    sa.Column('node', sa.String(length=30), nullable=True, comment='产生这一步的图节点名'),
    sa.Column('tool_name', sa.String(length=50), nullable=True),
    sa.Column('input_data', mysql.JSON(), nullable=True),
    sa.Column('output_data', mysql.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ok / failed'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_steps_run_id'), 'agent_run_steps', ['run_id'], unique=False)
    op.create_index('ix_agent_steps_run_seq', 'agent_run_steps', ['run_id', 'seq'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='会话归属用户'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='会话标题'),
    sa.Column('last_active_at', sa.DateTime(), nullable=False, comment='最后活跃时间，用于会话列表排序'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user / assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('run_id', sa.String(length=36), nullable=True, comment='这条消息由哪次运行产生'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_messages_conv_created', 'agent_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_conversation_id'), 'agent_messages', ['conversation_id'], unique=False)
    op.create_table('agent_pending_actions',
    sa.Column('action_id', sa.String(length=36), nullable=False, comment='对外暴露的操作 ID（UUID），不用主键是为了不泄露业务量级'),
    sa.Column('run_id', sa.String(length=36), nullable=False, comment='关联 agent_runs.run_id'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='确认后要回到哪个会话继续'),
    sa.Column('requested_by', sa.BigInteger(), nullable=False, comment='发起人'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='给用户看的一句话描述'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='low/medium/high'),
    sa.Column('payload', mysql.JSON(), nullable=False, comment='执行计划（工具名 + 参数 + 影响范围）'),
    sa.Column('affected_count', sa.BigInteger(), nullable=False, comment='影响行数'),
    sa.Column('preview', mysql.JSON(), nullable=True, comment='受影响对象摘要'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/approved/rejected/expired/executed/failed'),
    sa.Column('decided_by', sa.BigInteger(), nullable=True, comment='审批人'),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True, comment='审批意见 / 拒绝原因'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='超时时间，过期后不可再确认'),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('result', mysql.JSON(), nullable=True, comment='执行结果明细（含失败清单）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_pending_actions_action_id'), 'agent_pending_actions', ['action_id'], unique=True)
    op.create_index(op.f('ix_agent_pending_actions_expires_at'), 'agent_pending_actions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agent_pending_actions_requested_by'), 'agent_pending_actions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_agent_pending_actions_run_id'), 'agent_pending_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_pending_actions_status'), 'agent_pending_actions', ['status'], unique=False)
    op.create_index('ix_pending_status_expires', 'agent_pending_actions', ['status', 'expires_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False, comment='用户输入原文'),
    sa.Column('intent', sa.String(length=30), nullable=True, comment='识别出的意图'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='running/awaiting_approval/success/rejected/failed/cancelled'),
    sa.Column('answer', sa.Text(), nullable=True, comment='最终回答'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False, comment='输入 token'),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False, comment='输出 token'),
    sa.Column('tool_call_count', sa.BigInteger(), nullable=False, comment='工具调用次数'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='总耗时(毫秒)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间(UTC)'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_pending_status_expires', table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_status'), table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_run_id'), table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_requested_by'), table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_expires_at'), table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_action_id'), table_name='agent_pending_actions')
    op.drop_table('agent_pending_actions')
    op.drop_index(op.f('ix_agent_messages_conversation_id'), table_name='agent_messages')
    op.drop_index('ix_agent_messages_conv_created', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index('ix_agent_steps_run_seq', table_name='agent_run_steps')
    op.drop_index(op.f('ix_agent_run_steps_run_id'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    # ### end Alembic commands ###
